### ISSUE TITLE
Create new starter repository for MaptimeMileHigh

### ISSUE THREAD

**Issue by nateirwin** [maptime/starter#10]
Can you create a new repository for MaptimeMileHigh (named "denver"?) and give admin rights to myself (@nateirwin), @makella, and @nellconti?

Thanks!

**Comment by nateirwin** [comment]
BTW, this will replace the `denver` directory in the `maptime.github.io` repository.

Cc @geografa

**Comment by lyzidiamond** [comment]
Boom! Done: https://github.com/maptime/milehigh
