### ISSUE TITLE
Add Maptime Campinas (MaptimeCPS) repo

### ISSUE THREAD

**Issue by geografa** [maptime/starter#11]
- [x] add admin team 
- [ ] add chapter to map https://github.com/maptime/maptime.github.io/pull/172
- [x] assign team
- [x] import starter template

@tamielbr I'll need a list of your admins (Github usernames). Most Maptimes have 2-3.

/cc @lyzidiamond

**Comment by tamielbr** [comment]
Thanks (a bit of an amateur at github). 
@tamielbr and @gabrielfedel are the admins.

**Comment by geografa** [comment]
good to go:
- http://maptime.io/campinas/
- https://github.com/maptime/campinas

@tamielbr you will need to fix the chapter.json. looks like the latitude and longitude are backwards.

Let me know if that works out for you and if you have questions.

**Comment by tamielbr** [comment]
Done.
