### ISSUE TITLE
Clone repo as a submodule?

### ISSUE THREAD

**Issue by geobrando** [maptime/starter#2]
So I'd like to use the starter repo to build a jekyll page for the dc chapter and host at maptime.github.io/dc.  The problem is that we already have a dc repo.  My plan was to clone the starter repo and just add the code to a separate gh-pages branch, but I'd like to keep a link to your starter repo so I can pull in changes.

I know that you can add submodules.  I researched this but couldn't figure out if adding your repo as a submodule to a gh-pages branch would server a proper page at the appropriate subpath.  Know if this is possible?

**Comment by geografa** [comment]
> The problem is that we already have a dc repo

@geobrando what's wrong with keeping the dc repo as is but serving the pages from the gh-pages branch like Toronto? I think forking from starter would allow you to pull changes. That right @tristen ?

**Comment by geobrando** [comment]
@geografa Figured out a roundabout way to do it.  Forked, cloned locally, then set up our dc repo as a remote.  I was able to push the starter page to our dc repo as a new gh-pages branch, and I'll still be able to pull in any changes/improvements to this template using my local machine. Thanks.

**Comment by tristen** [comment]
@geobrando yep! that's the way to do it. I wouldn't consider Starter to be submodule or part of dependency tree. It should be forked with upstream changes merged via `git fetch upstream && git merge upstream/gh-pages`

**Comment by geografa** [comment]
@tristen this look right? I stumbled on this. Here's my process:

Clone and set remotes

```
git clone  git@github.com:maptime/starter.git
mv starter/ portland
cd portland/
git remote -help
git remote -v
git remote add upstream git@github.com:maptime/starter.git
git remote remove origin
git remote add origin git@github.com:maptime/portland.git
git fetch upstream && git merge upstream/gh-pages
```

This give me:

```
- origin    git@github.com:maptime/portland.git (fetch)
- origin    git@github.com:maptime/portland.git (push)
- upstream  git@github.com:maptime/starter.git (fetch)
- upstream  git@github.com:maptime/starter.git (push)
```

Now, we can:
- fetch from origin for recent changes
- push to orign with new branches or changes
- fetch from starter
- push to starter

Finally, push the new gh-pages branch to your city's repo:

`git push origin gh-pages`

**Comment by geobrando** [comment]
@geografa and @tristen  This is very similar to what I did, but I ended up with three remotes since I forked the starter to my individual account then cloned it, which was not necessary. Your way is a lot cleaner, geografa.

You could have done this and skipped a step

```
git clone  git@github.com:maptime/starter.git portland
```

Since new cities have to rely on an admin or owner to create a repo for them anyway, it would be ideal if you could just fork another copy of the starter for them in the Maptime organization (i.e. fork starter and renamed to portland).  But that's not currently allowed.  But you could do something similar from the command line.

I think this could all be scripted and run by an admin

```
curl -u 'maptime' https://api.github.com/orgs/maptime/repos -d '{"name":"Portland","description":"Repo for Maptime Portland"}'

git clone  git@github.com:maptime/starter.git portland
git remote add local git@github.com:maptime/portland.git
git push local gh-pages

curl -u 'maptime' https://api.github.com/orgs/maptime/teams -d '{"name":"us-portland-admin","permission":"admin","repo_names":"maptime/portland" 
curl -u 'maptime' -X PUT https://api.github.com/orgs/maptime/teams/:id/members/geografa
```

Using the github api, the first command creates a new repo for them, while the last two create an admin team, assigns to it the city repo, and adds a single local member to that team so they can manage it. The last command would require knowing the `:id` number for the team that was just created, but I'm sure there's a way to automate getting the id number.

If the new organizers aren't comfortable using the command line, they're now free to customize and add to their repo and pull in changes using the Github web interface and/or with prose.io.  If they want to use git, they can then do it in the typical way.

```
git clone git@github.com:maptime/portland.git
git remote add upstream git@github.com:maptime/starter.git
```

**Comment by geografa** [comment]
> Since new cities have to rely on an admin or owner to create a repo for them anyway, it would be ideal if you could just fork another copy of the starter for them in the Maptime organization (i.e. fork starter and renamed to portland). But that's not currently allowed. But you could do something similar from the command line.

@geobrando New maptime organizer cuts a ticket for a new repo, run the script, :boom:, done. I like where this is going :+1:

**Comment by geobrando** [comment]
@geografa Definitely necessary as this thing continues to grow like wildfire.  Realized there were some errors in my code.  I'm gonna fix it and try to write something up. If you guys use it, then great!  If not, still a cool project for me to write my first bash script.

**Comment by geobrando** [comment]
@geografa @almccon @bethschechter Is a script admins could use to create a clone of the starter repo for a city, along with an organizer assigned to an new admin team something you would find useful?  Or are you fine at this point with just doing it manually and leaving it up to them to figure out how to create their own Jekyll page from the template? Might be difficult for those new to git and github.

**Comment by bethschechter** [comment]
If a script to start a new page is helpful to make a new page, let's do it!

//typed with thumbs

**Comment by geografa** [comment]
I was really hoping to run this script but 2fa really got exponentially harder: https://developer.github.com/v3/auth/#working-with-two-factor-authentication

Any ideas here @geobrando ?

**Comment by geobrando** [comment]
@geografa Thanks for putting this back on my radar.  I have the whole thing worked out except the last part which is adding the admin to the team.  Expect a gist shortly.

**Comment by geografa** [comment]
zoops! added you

On Sun, Apr 26, 2015 at 4:53 PM, Brandon Knight notifications@github.com
wrote:

> @geografa https://github.com/geografa Thanks for putting this back on
> my radar. I have the whole thing worked out except the last part which is
> adding the admin to the team. Expect a gist shortly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maptime/starter/issues/2#issuecomment-96449206.

## 

Rafa Gutierrez
help@mapbox.com
