### ISSUE TITLE
Next event is not accurate

### ISSUE THREAD

**Issue by nomoregrapes** [maptime/starter#22]
On the homepage it shows a box with the "Next Event". This simply gets the event furthest into the future and is normally okay. If a chapter schedules multiple events into the future, then it will be wrong.

The fix would be to get the earliest event that is past the current date. I'm not familiar with Jekyll but hopefully this is easy to do.

**Comment by geobrando** [comment]
@tristen Is this an easy fix?

**Comment by tristen** [comment]
Hey - missed this. pr to fix it here: https://github.com/maptime/starter/pull/24
