### ISSUE TITLE
New MaptimeKC chapter

### ISSUE THREAD

**Issue by RiverDoctor** [maptime/starter#6]
we would like to start a new chapter in Kansas and need to set up our website. any help will be appreciated.

**Comment by geobrando** [comment]
Hey @RiverDoctor . Have you made any progress with this?  Best way to get started is to send an email to hello@maptime.io. They'll respond and help you get set up.

**Comment by geografa** [comment]
Sorry for the delay @RiverDoctor ! Repo is made - let me know if you have any issues! https://github.com/maptime/kansas-city

Don't forget to update the _config.yml for your site (it's in the readme).
