### ISSUE TITLE
Site for MaptimeMSP

### ISSUE THREAD

**Issue by mtaylorlong** [maptime/starter#9]
@geografa 
MaptimeMSP is ready to set up our own site at maptime.io/msp. Will you create a new repository (named "msp") under the Maptime organization account and include our chapter's organizers to administer it? We're delighted to use Starter – it looks simple and lovely.

MaptimeMSP Organizers Github Usernames:
mtaylorlong
lpuhl
fawcett
bitner

Let me know if you need anything else from me. No rush on this. Thanks for your help!

**Comment by geografa** [comment]
Cool. Thanks - you're live: 
- http://maptime.io/msp/
- https://github.com/maptime/msp

Let me know if you have questions.
